### ISSUE TITLE
Process the scene dataset

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#3]
- Create or research about an object detector,
- Separate the mesh into different objects,

**Comment by andrefdre** [comment]
Two approaches were suggested, one to process the mesh directly and retrieve the objects by eliminating noise, while the other is based in an object detector to estimate the objects.
Two new issues will be created to explore each approach.

**Comment by TatianaResend** [comment]
Followed up with Approach number 1: Retrieve objects based on mesh processing #7
