### ISSUE TITLE
Point cloud of .bag files does not display the table

### ISSUE THREAD

**Issue by TatianaResend** [andrefdre/Dora_the_mug_finder_SAVI#38]
When opening the Point cloud of the files created with rosbag it doesn't show the table, it probably has to do with the color of the table, since with a brown table it worked correctly.

<img src="https://user-images.githubusercontent.com/101273005/213311403-173aabc6-be3d-4cae-9ceb-f43ee29ac6a2.png" width=60% height=60%>

**Comment by TatianaResend** [comment]
In the function pc2.read_points() the skip_nans parameter: If True, then don't return any point with a NaN value and then you can set it to false (default value) and all points will appear.

<img src="https://user-images.githubusercontent.com/101273005/213312103-2222ae83-dd47-4e8e-8521-046c6c1b2328.png" width=60% height=60%>

**Comment by andrefdre** [comment]
Please add that to the documentation and if you are bored and don't wanna code create a wiki with all that and the kinect information. 
Also, please add the rosbag from motochanics room to the cloud so all people have access.
