### ISSUE TITLE
Get the properties about the classified object

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#4]
Properties to be detected:
- color
- height
- width
- other relevant properties

**Comment by TatianaResend** [comment]
The height, width and depth can be known through the bbox points.
<img src="https://user-images.githubusercontent.com/101273005/209857220-4db06a22-2b3f-46f4-ba44-f447b432c93e.png" width=30% height=30%>

**Comment by TatianaResend** [comment]
To remove the height, width and length properties one could have used ```get_max_extent(self)```.
http://www.open3d.org/docs/latest/python_api/open3d.geometry.AxisAlignedBoundingBox.html#open3d.geometry.AxisAlignedBoundingBox.get_max_extent

But it has the following error:
```AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'get_max_extent'```

So we chose to do it in two steps, with ```get_max_extent(self)``` and ```get_min_extent()```.

**Comment by TatianaResend** [comment]
Options to analyze to discover the color of objects:
- Calculate the RGB components for isolated points of the point cloud and average.
- Calculate the RGB components in the 2D image used for the classifier.

**Comment by TatianaResend** [comment]
Any ideas for properties other than height, length, width, and color? @andrefdre e @fabio-rcs

**Comment by fabio-rcs** [comment]
It's only missing the property color now. We defined that it will be obtained with the 2D image.

**Comment by andrefdre** [comment]
We should also think about what other features we can add. We could also print the ratio of the object even though it is already described with height and width.

**Comment by TatianaResend** [comment]
Missing: Confirm that the height, length and width properties are well calculated and that the values make sense.

**Comment by TatianaResend** [comment]
In the image_extractor file, remove the object's color and send it via ROS message.

**Comment by TatianaResend** [comment]
To set the color of the object, we have two methods:
- find out the values of the r, g, b components and come up with a function to find the color
- find out the values of the hsv components and define h-value ranges according to 8 possible colors (violet, blue, green, yellow, orange, red, white and black)

**Comment by TatianaResend** [comment]
The color of the object is obtained from a little square in the center of the object of size 5x5, which in a case like the cereal box can lead to error. Anyway, I think this is the best way for most objects.

**Comment by TatianaResend** [comment]
The search for color changed, instead of fetching from 2D images as originally planned, it was decided to fetch from 3D objects as it showed better results (compared to getting color from 2D images).

**Comment by TatianaResend** [comment]
Corrections in obtaining height, length and width properties:
- Changing the place where the properties are calculated (after the transformation of the objects to the initial position)
- Change the height with the width
