### ISSUE TITLE
Scenarios 5-8 and 13 object extraction (2D) does not work

### ISSUE THREAD

**Issue by TatianaResend** [andrefdre/Dora_the_mug_finder_SAVI#43]
Scenes 5-8 and 13 don't have the z axis of the camera pointing to the table, so object extraction (2D) doesn't work, because the first scene image doesn't have any objects.

You need to implement a system that:
- read the various images
- recalculate the position of objects (in 2D) as the camera rotates
- select the image that has all objects included

**Comment by andrefdre** [comment]
Hi, I was thinking about this and I thought one good first try is to pick up the scene poses for each image and use that as the rotation and translation matrix. Do you think it makes sense?

**Comment by TatianaResend** [comment]
> Hi, I was thinking about this and I thought one good first try is to pick up the scene poses for each image and use that as the rotation and translation matrix. Do you think it makes sense?

I tried this suggestion, but the results were not positive.
Either it happened to get caught in the middle of the images, or else it gave an error.
![Screenshot from 2023-01-19 16-26-32](https://user-images.githubusercontent.com/101273005/213529939-ffe90180-b497-4e36-bb3c-86d5a9cfdec1.png)

```
[ERROR] [1674151865.892081]: bad callback: <bound method Image.callback of <__main__.Image object at 0x7f1c85eef9a0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/tatiana/catkin_ws/src/Dora_the_mug_finder_SAVI/dora_the_mug_finder_bringup/scripts/image_extractor.py", line 93, in callback
    self.cropped_images.images.append(self.bridge.cv2_to_imgmsg(cropped_image, "passthrough"))
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 271, in cv2_to_imgmsg
    img_msg.step = len(img_msg.data) // img_msg.height
ZeroDivisionError: integer division or modulo by zero

```

I'm not sure what each value in the .pose file represents, but I think it's quaternium (w,x,y,z) and translation (x,y,z).
I'm just sure that the first value corresponds to w.

In researching the documentation, it is only reported that the .pose file is "3D scene reconstruction camera pose estimates"

**Comment by TatianaResend** [comment]
The previous approach is probably wrong. I think it is also necessary to take into account the transformation of the camera and not just those of the points.
If I only have those of the points, what happens is that I represent the transformation of the points relative to the reference point of the current camera position, but the image is seen from the position of the first camera.
 
Result: The dots appear within the image, but appear to be inverted.
I have already reviewed the operations of the matrices and apparently they are correct.

![Screenshot from 2023-01-21 07-31-24](https://user-images.githubusercontent.com/101273005/213863968-189aeb71-2874-4e44-9142-e245f8b99640.png)

**Comment by TatianaResend** [comment]
> The previous approach is probably wrong. I think it is also necessary to take into account the transformation of the camera and not just those of the points. If I only have those of the points, what happens is that I represent the transformation of the points relative to the reference point of the current camera position, but the image is seen from the position of the first camera.
> 
> Result: The dots appear within the image, but appear to be inverted. I have already reviewed the operations of the matrices and apparently they are correct.
> 
> ![Screenshot from 2023-01-21 07-31-24](https://user-images.githubusercontent.com/101273005/213863968-189aeb71-2874-4e44-9142-e245f8b99640.png)

This approach was not correct, since when taking into account the rotation of the camera and the rotation of the points, it overlapped, that is, it was as if it did nothing.

**Comment by TatianaResend** [comment]
The correct approach is shown in the figure.

<img src="https://user-images.githubusercontent.com/101273005/213895328-1265ecbd-1128-4977-a673-54b715c2803f.jpeg" width=50% height=50%>



Note: the order in the .pose file is QW,QX,QY,QZ,x,y,z

**Comment by TatianaResend** [comment]
It remains to run the images in a loop to see which is the first image that contains all the objects

**Comment by TatianaResend** [comment]
When we first got the min and max values to draw the bbox it was from the camera perspective. Now when searching other camera positions it can be the other way around, so the min and max can be swapped. To fix this we need to first check what is higher and then swap.

**Comment by TatianaResend** [comment]
Bbox points are not always in the same order [xmin ymax, xmax ymin], sometimes ymax and ymin are switched.
A simple way, in the program, is to ignore these cases and try another image with another camera position.

<img src="https://user-images.githubusercontent.com/101273005/215060348-9d2f9539-3205-4456-8760-7e2221b15945.png" width=60% height=60%>

In the particular case of scene 13, the 3rd image is not cropped well. But it is an isolated case, so it will only get better if easy to implement ideas come up.

**Comment by andrefdre** [comment]
Instead of using bbox to extract object images instead I do an intermidiate step to calculate width and height. So the center will always be in the middle of the extracted images. 
```
width = bbox_2d[idx][1][0][0] - bbox_2d[idx][0][0][0]
height = bbox_2d[idx][0][0][1] - bbox_2d[idx][1][0][1]
cropped_image = image[round(point_2d[0][1]-height/2):round(point_2d[0][1]+height/2),round(point_2d[0][0]-width/2):round(point_2d[0][0]+width/2)]
```

**Comment by TatianaResend** [comment]
The problem is solved and even if I added the search for the best image of each object taking into account the overlapping of images (with an adaptation of the iou method).
