### ISSUE TITLE
Update requirements text and add requirements install line to README

### ISSUE THREAD

**Issue by fabio-rcs** [andrefdre/Dora_the_mug_finder_SAVI#48]
Include in the requirements text file all the packages used and update README with the line to install all the requirements.

**Comment by fabio-rcs** [comment]
With this [commit](https://github.com/andrefdre/Dora_the_mug_finder_SAVI/commit/f4332053b121ef9ea6362c0f7ed6988b7dbbff61) I think I already did most of the necessary updates. A review is pending to the new changes.

**Comment by andrefdre** [comment]
I would suggest maintaining the original files and just create 2 new launch files. One to launch the kinect and one that launches all the other launch files.
So the user can choose in this last one to run with kinect or rosbag. Also in the README there should stay the code to just launch the code without kinect as it is right now.

**Comment by fabio-rcs** [comment]
With all the suggestions implemented, now it's only missing a new review by my peers (@andrefdre  and @TatianaResend), so that this issue can be closed.

**Comment by andrefdre** [comment]
Features implemented.
