### ISSUE TITLE
Describe scene with audio

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#5]
Describe the objects detected in the scene with Google api.

**Comment by andrefdre** [comment]
We should focus on this now.

**Comment by fabio-rcs** [comment]
With commit [9093028](https://github.com/andrefdre/Dora_the_mug_finder_SAVI/commit/90930283a4afc8f11c16a9f99e5b6d2f694cb5b5), it's only missing the color of the objects.

**Comment by fabio-rcs** [comment]
Still missing the implementation of color and addition to launch file

**Comment by fabio-rcs** [comment]
With commit [244a7b4](https://github.com/andrefdre/Dora_the_mug_finder_SAVI/commit/244a7b4ac1b9f712d5b1a8fe138fd846cc220979) this issue can now be closed.
