### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#55]
Some links aren't working.
We need to record a video for demonstrating.
Improve documentation.

**Comment by andrefdre** [comment]
We can also add a wiki with installation of ROS and kinect.

**Comment by andrefdre** [comment]
The bugs were fixed now just the wiki and recording video is left to be implemented.

**Comment by TatianaResend** [comment]
The demo video is already published on YouTube and the link is in the README (view demo).

**Comment by fabio-rcs** [comment]
README and WIKI are finalized. Just pending approval by @andrefdre and @TatianaResend.

**Comment by fabio-rcs** [comment]
After receiving feedback, everything is ok and this issue can now be closed.
