### ISSUE TITLE
Use kinect camera to test the code live

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#6]
Use the kinect camera to test the code live

**Comment by andrefdre** [comment]
We need to capture a rosbag of the camera to ease programming at home.

**Comment by TatianaResend** [comment]
> We need to capture a rosbag of the camera to ease programming at home.

The part of creating a rosbag is in the issue #30

**Comment by TatianaResend** [comment]
The sending of the point cloud message has not yet been implemented, but it is already possible to visualize the point cloud extracted from the kinet in open3d format.

![Screenshot from 2023-01-18 01-25-34](https://user-images.githubusercontent.com/101273005/213058139-cd9ff309-cb01-4fad-8f9c-f10b9117442d.png)

**Comment by TatianaResend** [comment]
It will probably also be necessary to send the RGB image and depth in order to be able to extract the objects in 2D to do the classification.
It is necessary to confirm but I think the topics for the RGB image is: ```/camera/rgb/image_rect_colorand ``` for the depth is: ``` /camera/depth_registered/image ```

**Comment by TatianaResend** [comment]
Cautions/code changes (retrieve objects):
- open point cloud directly (not through .pcd); the filename will be the one you get from topic "\cloud"
```
point_cloud_original = o3d.io.read_point_cloud(filenames[0])
```
- table plane detection does not go through plane selection phase
``` 
plane_table = PlaneDetection(point_cloud_original) # create a new plane instance
plane_table.segment() # new point cloud are the outliers of this plane detection
```

**Comment by TatianaResend** [comment]
While the message is not created, the code can be tested by recording the point cloud and when objects are detected, the point cloud is opened, instead of receiving the message directly from the camera or from the bag file.

**Comment by TatianaResend** [comment]
Table plane detection works correctly, but object detection is having issues. I still don't know how to solve it.

<img src="https://user-images.githubusercontent.com/101273005/213317738-f06423a8-fb42-43b1-b40c-2d91832a4df9.png" width=60% height=60%>

**Comment by TatianaResend** [comment]
I was able to improve plane detection by modifying the ```cluster_dbscan``` parameters, namely by increasing the ```eps``` value that defines the distance to neighbors in a cluster.

<img src="https://user-images.githubusercontent.com/101273005/213324763-df57cce3-dc40-4d73-8def-6a483507790c.png" width=60% height=60%>

**Comment by TatianaResend** [comment]
This is in standby while #39 is being worked upon.

**Comment by andrefdre** [comment]
The whole pipeline of the kinect is working but right now the extracted images don't loo good, maybe it is the camera calibration.

**Comment by TatianaResend** [comment]
Need to improve image extraction (from 3D to 2D).

**Comment by TatianaResend** [comment]
Good live object detection:
![Captura de ecrã 2023-01-30 145152](https://user-images.githubusercontent.com/101273005/215511397-160b5dd6-5693-427a-a0d8-572cd46c2772.png)
