### ISSUE TITLE
Approach number 1: Retrieve objects based on mesh processing

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#7]
Use the tools of open3D.

**Comment by TatianaResend** [comment]
![Screenshot from 2022-12-28 15-39-07](https://user-images.githubusercontent.com/101273005/209849367-4116795c-099f-416b-a3d0-4a6f3509c00d.png)

**Comment by andrefdre** [comment]
In the open3d tutorials there is a part where they mention that images can be captured from the scene. Maybe this can help, it is under the topic **Capture images in a customized animation**, both color image and depth image are captured using `Visualizer.capture_depth_float_buffer` and `Visualizer.capture_screen_float_buffer respectively`. The images are saved as png files.
http://www.open3d.org/docs/release/tutorial/visualization/customized_visualization.html

**Comment by andrefdre** [comment]
> In the open3d tutorials there is a part where they mention that images can be captured from the scene. Maybe this can help, it is under the topic **Capture images in a customized animation**, both color image and depth image are captured using `Visualizer.capture_depth_float_buffer` and `Visualizer.capture_screen_float_buffer respectively`. The images are saved as png files. http://www.open3d.org/docs/release/tutorial/visualization/customized_visualization.html

I implemented the tutorial I mentioned, and it worked now we just need to figure out how to center in the object and take a picture for each object. I also noticed the objects don't have good definition, it would be better to create a copy of the original point cloud, do all the down sampling on that one. After figuring out the bounding box of the object, take the point cloud from the original one.

Result:
![Screenshot from 2022-12-28 21-52-11](https://user-images.githubusercontent.com/58526188/209876460-7ec4cc16-efa9-4187-bfd1-60379688413e.png)

**Comment by TatianaResend** [comment]
### **Objects appear clipped.** 
It is necessary to review the code and correct.
![Screenshot from 2022-12-28 22-40-59](https://user-images.githubusercontent.com/101273005/209885101-dd918cb5-23cf-4c8c-b5d0-9388de0380ef.png)

If possible, when reviewing the code, try to clean it up and make it more universal.

**Comment by TatianaResend** [comment]
It is necessary to be able to align the point cloud.

https://stackoverflow.com/questions/62596854/aligning-a-point-cloud-with-the-floor-plane-using-open3d  
With the technique presented in the link it did not work, probably the math is wrong.
It is also not possible to guarantee that the plane found is the floor or the table.

**Comment by TatianaResend** [comment]
The purpose of aligning the point cloud is with the table plane if you can draw a bbox with the points above the table plane, to proceed with the retrieve objects.

**Comment by andrefdre** [comment]
The open3d has dbscan for clustering, which showed to not be consistent. After some research I found this link https://towardsdatascience.com/3d-point-cloud-clustering-tutorial-with-k-means-and-python-c870089f3af8, which showed promising results. It also has a comparison beetwen dbscan and k-means, showing k-means can be interesting in some cases.

**Comment by TatianaResend** [comment]
The table plane is always caught in the first two planes.
When the planes are the table and the floor:
- the difference in the d component of each plane is greater than 0.3.
 -If the difference is positive, the 2nd plane is detected.
 -If the difference is negative, the 1st plane is detected.

When planes are table and other (d component < 0.3):
- the table plane is the 1st detected plane.

**Comment by TatianaResend** [comment]
> The open3d has dbscan for clustering, which showed to not be consistent. After some research I found this link https://towardsdatascience.com/3d-point-cloud-clustering-tutorial-with-k-means-and-python-c870089f3af8, which showed promising results. It also has a comparison beetwen dbscan and k-means, showing k-means can be interesting in some cases.

I got the dbscan for clustering to be consistent, it's probably a matter of correctly setting the clustering parameters (eps, min_points) and those of the voxel_down_sample.

**Comment by TatianaResend** [comment]
To be able to retrieve objects based on mesh processing:
- Find two planes: from the table and another
- Choose between the plans the table plan
- Definition point cloud without table and point cloud only table
- Find table
- Frame alignment
- Select the bounding box of the table with the objects
- Cut the point cloud by bounding box
- Select and calculate object properties
