### ISSUE TITLE
Approach number 2: Retrieve the objects with object detector

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Dora_the_mug_finder_SAVI#8]
Some general research is needed.

**Comment by TatianaResend** [comment]
What you find most is detection with recognition, using YOLO (Yolov3, Yolov5, tiny Yolov3), caffe, and others.

**Comment by TatianaResend** [comment]
In some cases, to detect objects you can train a single-class model by simply setting all of your training data to the same class 0, or by forcing a multi-class dataset like COCO into single class using.
[https://github.com/ultralytics/yolov3/issues/821](url)

**Comment by TatianaResend** [comment]
## **Votenet: Deep Hough Voting for 3D Object Detection in Point Clouds**
It looked promising, and I lost an afternoon back from this one, but I didn't get good results
It can be found at: 
[https://github.com/charlesq34/votenet-1](url)
[https://github.com/erikwijmans/Pointnet2_PyTorch](url)
[https://github.com/lanlan96/3DRM/tree/master/VoteNet-RM](url)

Major Problems:
— Several bugs in the code, but there was one bug I couldn't solve where it involved CUDA
— It's a lot of code, and it takes a long time to run

**Comment by andrefdre** [comment]
> Several bugs in the code, but there was one bug I couldn't solve where it involved CUDA

Could you paste the error message you get?

**Comment by TatianaResend** [comment]
> Could you paste the error message you get?

```Pointnet2_PyTorch** git:(master) pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Processing ./pointnet2_ops_lib
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/tatiana/catkin_ws/src/Pointnet2_PyTorch/pointnet2_ops_lib/setup.py", line 27, in <module>
          CUDAExtension(
        File "/home/tatiana/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/tatiana/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/tatiana/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by TatianaResend** [comment]
The most promising solution is to use YOLO and set all your training data to the same class 0.
https://github.com/ultralytics/yolov3

Most object detectors already do the classification, as they search the scene for objects they know
